### CREATE EVENT
POST http://localhost:8080/events
Content-Type: application/json

{
  "title": "Campeonato Paulista 2024",
  "details": "Santos Campeão",
  "maximumAttendees": 40000
}


### GET EVENT
GET http://localhost:8080/events/148330e8-0cd3-4ffa-b562-c2e4f69835f8
Content-Type: application/json

### GET EVENT ATTENDEES
GET http://localhost:8080/events/attendees/148330e8-0cd3-4ffa-b562-c2e4f69835f8
Content-Type: application/json

### REGISTER PARTICIPANT
POST http://localhost:8080/events/148330e8-0cd3-4ffa-b562-c2e4f69835f8/attendees
Content-Type: application/json

{
  "name": "Cassiru",
  "email": "test@gmail.com"
}

### GET BADGE
GET http://localhost:8080/attendees/74b8ee7e-80aa-4907-9e20-380cbb3bddd9/badge
Content-Type: application/json